# Generated by Django 3.2.6 on 2021-10-04 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_rename_payment_id_orderpay_paymentid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderpay',
            old_name='paymentid',
            new_name='pay',
        ),
    ]
