# Generated by Django 3.2.6 on 2021-10-04 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_rename_paymentid_orderpay_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='orderstatus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='payment.order'),
        ),
        migrations.DeleteModel(
            name='orderpay',
        ),
    ]
