# Generated by Django 3.2.6 on 2021-09-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='usr_gender',
            field=models.IntegerField(),
        ),
    ]
