# Generated by Django 3.2.6 on 2021-09-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_alter_register_usr_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='usr_role',
            field=models.IntegerField(default=1),
        ),
    ]
