# Generated by Django 3.2.6 on 2021-09-23 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_login_usr_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='usr_loginid',
        ),
        migrations.DeleteModel(
            name='login',
        ),
        migrations.DeleteModel(
            name='register',
        ),
    ]
