# Generated by Django 3.2.6 on 2021-09-23 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0004_auto_20210923_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr_email', models.EmailField(max_length=254)),
                ('usr_passw', models.CharField(max_length=150)),
                ('usr_role', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr_name', models.CharField(max_length=150)),
                ('usr_gender', models.IntegerField()),
                ('usr_phone', models.CharField(max_length=150)),
                ('usr_loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.login')),
            ],
        ),
    ]
