# Generated by Django 3.2.6 on 2021-09-27 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_country'),
        ('userapp', '0005_login_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='adreess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_state', models.CharField(max_length=150)),
                ('ad_adres1', models.CharField(max_length=150)),
                ('ad_adres2', models.CharField(max_length=150)),
                ('ad_town', models.CharField(max_length=150)),
                ('ad_pin', models.BigIntegerField()),
                ('ad_phone', models.BigIntegerField()),
                ('ad_countryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.country')),
                ('ad_userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.register')),
            ],
        ),
    ]
