# Generated by Django 3.2.6 on 2021-10-05 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_adreess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='usr_phone',
        ),
    ]
